config/routes.rb
Rails.application.routes.draw do

   root 'chairs#index'
   resources :chairs

   get 'sign-up', to: 'registrations#new'
   post 'sign-up', to: 'registrations#create'
   get 'sign-out', to: 'auth#destroy'
   get 'sign-in', to: 'auth#new'
   post 'sign-in', to: 'auth#create'

end

app/models/chair.rb
class Chair < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user
  
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Thank you for signing in!"
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    reset_session
    flash[:notice] = "Goodbye!"
    redirect_to root_path
  end
end

app/controllers/chairs_controller.rb
class ChairsController < ApplicationController
  before_action :set_chair, only:[:show, :edit, :update]

  def index
    @chairs = Chair.all
  end

  def show
  end

  def new
    @chair = Chair.new
  end

  def create
    chair = Chair.new(chair_params)
    if chair.save
      flash[:notice] = "You successfully saved a chair!"
      redirect_to chair_path(chair)
    else
      @chair = chair
      render :new
    end
  end

  def edit
  end

  def update
    if @chair.update(chair_params)
      flash[:notice] = "You successfully updated a chair!"
      redirect_to chair_path(@chair)
    else
      render :edit
    end
  end

  def destroy
    chair = Chair.find(params[:id])
    chair.destroy
    flash[:notice] = "You successfully deleted a chair"
  end

  private

  def chair_params
    params.require(:chair).permit(:name, :age)
  end

  def set_chair
    @chair = Chair.find(params[:id])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(params.require(:user).permit(:email, :password, :password_confirmation))
    if user.save
      flash[:notice] = "Thank you for Signing up!"
      session[:user_id] = user.id
      redirect_to root_path
    else
      @user = user
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chairs/_form.haml
= form_for @chair do |f|
  = f.label :name
  = f.text_field :name
  = f.label :age
  = f.text_field :age
  = f.submit
= link_to 'Back', chairs_path

app/views/chairs/edit.haml
= render 'form'

app/views/chairs/index.haml
= link_to 'New Chair', new_chair_path
- @chairs.each do |chair|
  %p= chair.name
  %p= chair.age
  = link_to 'Edit', edit_chair_path(chair)
  = link_to 'Delete', chair_path(chair)

app/views/chairs/new.haml
= render 'form'

app/views/chairs/show.haml
= @chair.name
= @chair.age

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChairsAppWithAuth
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if flash[:notice]
      = flash[:notice]
    - if current_user
      = link_to 'Sign Out', sign_out_path
    - else
      = link_to 'Sign In', sign_in_path
      = link_to 'Sign Up', sign_up_path
    = yield